name: windows-build
on:
  workflow_dispatch:  # 添加手动触发

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      BOOST_ROOT: C:\local\boost_1_82_0
    steps:
      - uses: actions/checkout@v4
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.13
      - name: Configure OS
        shell: bash
        env:
          CONTINUOUS_INTEGRATION: true
        run: |
          ./acore.sh install-deps
      - name: Build
        shell: bash
        run: |
          export CTOOLS_BUILD=all
          export CTYPE=RelWithDebInfo
          ./acore.sh compiler build
      - name: Package Build Artifacts
        if: success()
        run: |
          tar -czvf azerothcore-windows.tar.gz -C ./env/dist .
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: azerothcore-windows
          path: azerothcore-windows.tar.gz
